import { Router } from "express";
import userRoutes from "@routes/user.routes";
import authRoutes from "@routes/auth.routes";
import customerRoutes from "@routes/customer.routes";
import deliveryAddress from "@routes/deliveryAddress.routes";
import productRoutes from "@routes/product.routes";
import supplierRoutes from "@routes/supplier.routes";
import unityRoutes from "@routes/unity.routes";
import productDefinitionRoutes from "@routes/productDefinition.routes";
import warehouseRoutes from "@routes/warehouse.routes";
import inventoryMovementRoutes from "@routes/inventoryMovement.routes";
import lotRoutes from "@routes/lot.routes";
import recipeRoutes from "@routes/recipe.routes";
import recipeItemRoutes from "@routes/recipeItem.routes";
import productionOrderRoutes from "@routes/productionOrder.routes";
import productionOrderInputRoutes from "@routes/productionOrderInput.routes";
import saleOrderRoutes from "@routes/saleOrder.routes";
import saleOrderItemRoutes from "@routes/saleOrderItem.routes";
import purchaseOrderRoutes from "@routes/purchaseOrder.routes";
import purchaseOrderItemRoutes from "@routes/purchaseOrderItem.routes";
import accountsReceivableRoutes from "@routes/accountsReceivable.routes";
import accountsPayableRoutes from "@routes/accountsPayable.routes";
import financialTransactionRoutes from "@routes/financialTransaction.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/customers", customerRoutes);
router.use("/delivery-address", deliveryAddress);
router.use("/products", productRoutes);
router.use("/unities", unityRoutes);
router.use("/product-definitions", productDefinitionRoutes);
router.use("/suppliers", supplierRoutes);
router.use("/warehouses", warehouseRoutes);
router.use("/inventoryMovement", inventoryMovementRoutes);
router.use("/lots", lotRoutes);
router.use("/recipes", recipeRoutes);
router.use("/recipe-items", recipeItemRoutes);
router.use("/production-orders", productionOrderRoutes);
router.use("/production-order-inputs", productionOrderInputRoutes);
router.use("/sale-orders", saleOrderRoutes);
router.use("/sale-order-items", saleOrderItemRoutes);
router.use("/purchase-orders", purchaseOrderRoutes);
router.use("/purchase-order-items", purchaseOrderItemRoutes);
router.use("/accounts-receivable", accountsReceivableRoutes);
router.use("/accounts-payable", accountsPayableRoutes);
router.use("/financial-transactions", financialTransactionRoutes);

export default router;
